### ISSUE TITLE
Default options for  CMake build on Windows with Visual Studio that work?

### ISSUE THREAD

**Issue by mkuitune** [adobe/lagrange#2]
### Expected Behaviour

It would be nice if the build would "just work" without configuration with some moderately sane defaults on Windows with Visual Studio toolchain. 

### Actual Behaviour

The CMake UI Configuration step produces quite many errors, which it is not obvious how to clear up. Please see the cmake output at the end. 

#### Steps to Reproduce

Download latest Lagrange release (5.1.0) to Windows 10 desktop with CMake gui tool and Visual Studio (e.g. 2019) installed. Run the CMake configuration.

#### Platform and Version

Windows 10, Visual Studio 2019, CMake 3.2.1, Lagrange v. 5.10, 

#### Logs taken while reproducing problem

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
Third-party (external): creating target 'Catch2::Catch2'
Lagrange: creating target 'lagrange::core'
Third-party (external): creating target 'Eigen3::Eigen'
Third-party (external): creating target 'igl::core'
MSVC -> forcing use of dynamically-linked runtime.
Creating target: igl::core (igl)
Third-party (external): creating target 'spdlog::spdlog'
Build spdlog: 1.6.1
Build type: Release
Generating install
Third-party (external): creating target 'TBB::tbb'
Lagrange: creating target 'lagrange::testing'
Lagrange: creating target 'lagrange::io'
Lagrange: creating target 'lagrange::fs'
Third-party (external): creating target 'filesystem::filesystem'
Third-party (external): creating target 'tinyobjloader::tinyobjloader'
CMake Error at cmake/lagrange/lagrange_include_modules.cmake:15 (add_subdirectory):
  add_subdirectory given source
  "D:/Incoming/srctest/lagrange-5.1.0/modules/serialization" which is not an
  existing directory.
Call Stack (most recent call first):
  modules/testing/CMakeLists.txt:31 (lagrange_include_modules)

Using test data folder: D:/Incoming/srctest/lagrange-5.1.0/data
Third-party (external): creating target 'CLI11::CLI11'
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen not found, building docs has been disabled
Lagrange: creating target 'lagrange::ui'
CMake Error at modules/ui/CMakeLists.txt:43 (include):
  include could not find requested file:

    nanoflann

Third-party (external): creating target 'gl3w::gl3w'
Third-party (external): creating target 'glfw::glfw'
Using Win32 for window creation
Third-party (external): creating target 'stb::stb'
Third-party (external): creating target 'imgui::imgui' ('docking' branch)
Third-party (external): creating target 'imguizmo::imguizmo'
Third-party (external): creating target 'imgui::fonts'
Third-party (external): creating target 'nativefiledialog::nativefiledialog'
Third-party (external): creating target 'nlohmann_json::nlohmann_json'
Lagrange: creating target 'lagrange::assets'
Third-party (external): creating target 'EnTT::EnTT'
Populating copy rules for target: test_lagrange_core
Populating copy rules for target: test_lagrange_fs
Populating copy rules for target: test_lagrange_io
Populating copy rules for target: ui_playground
Populating copy rules for target: ui_show_attribute
Populating copy rules for target: ui_dynamic_mesh
Populating copy rules for target: ui_scene
Populating copy rules for target: ui_callbacks
Populating copy rules for target: ui_treenode
Populating copy rules for target: test_lagrange_ui
Populating copy rules for target: remove_duplicate_vertices
Populating copy rules for target: predicates_speed
Populating copy rules for target: refine_mesh
Populating copy rules for target: remove_degenerate_triangles
Populating copy rules for target: remove_short_edges
Populating copy rules for target: mesh_initialization
Populating copy rules for target: connectivity
Populating copy rules for target: components
Populating copy rules for target: dijkstra
Populating copy rules for target: select_vertices_speed
Populating copy rules for target: resolve_nonmanifoldness
Populating copy rules for target: repeated_loading
Populating copy rules for target: condense_uv
Populating copy rules for target: marquee
Populating copy rules for target: array
Populating copy rules for target: unify_index_buffer
Populating copy rules for target: view_tangent_frame
Populating copy rules for target: mesh_cleanup
Configuring incomplete, errors occurred!
See also "D:/Incoming/srctest/lagrange-5.1.0/out/CMakeFiles/CMakeOutput.log".
See also "D:/Incoming/srctest/lagrange-5.1.0/out/CMakeFiles/CMakeError.log".

**Comment by qnzhou** [comment]
Thanks, @mkuitune, for reporting this problem!  We will release a fix soon!

**Comment by HasKha** [comment]
Fixed with 8025f98c6e4590abdd73ddcf302e339bb5d6b9df
